### PR TITLE
Refactor Tests Infra

### PR DESCRIPTION
**Pull request by liav-certora**
This PR aims to expand the tests infrastructure for CVLDoc. 
Currently, adding new tests will require writing a python function for each test individually.
This PR mainly automates this task such that no meddling with the python code will be required. To add a new test, only the spec and expected are required in the tests dir and nothing else.
Also done in this PR is an adding better CI workflow. Currently a version of cvldoctool will be published on every commit to every PR, which isn't good. A new workflow has been added to only test the build on every commit and for publishing a new version, a manual trigger will be required. Another little improvement is an integration with the Tests tab on CircleCI for better results showing.

### CODE REVIEW

**Comment by pickx** [comment]
hey, thanks for the PR.

can you explain the changes you're making here? in particular: 
- what is the aim of this PR?
- why have you commented out all of the tests?
- why have you made various style changes to existing code?

also, I'm using [black](https://pypi.org/project/black/) to format code in this project. please use this as well for the sake of standardization.

**Comment by liav-certora** [comment]
> hey, thanks for the PR.
> 
> can you explain the changes you're making here? in particular:
> 
> * what is the aim of this PR?
> * why have you commented out all of the tests?
> * why have you made various style changes to existing code?
> 
> also, I'm using [black](https://pypi.org/project/black/) to format code in this project. please use this as well for the sake of standardization.

* I updated the description of the PR to explain its aim.
* I need to remove these files actually, I commented these tests because they are already running by a different function that runs all the tests.
* I have different reasons for different changes, you are more than welcome to comment on specific changes and I'll do my best to explain my choices.

I am not very familiar with using black, so I'll check this out. But of course, no problem :)

Also, you may want to take a look at this example of how the workflow runs now: https://app.circleci.com/pipelines/github/Certora/cvldocTool/129/workflows/63fe6e0e-0b57-4b0a-9293-520cbc89a06c/jobs/202

**Comment by pickx** [comment]
looks fine now. thanks!

**Review by pickx — APPROVED** [review]
looks fine. thanks!

**Pull request merged**
